#!/bin/bash

mkdir Transfer2

cd Transfer2

mkdir DASTRIMTRIM
echo "DASTRIMTRIM"

echo "-1000"

cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-1.0V/main.RHO ./DASTRIMTRIM/-1000.RHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-1.0V/main.DRHO ./DASTRIMTRIM/-1000.DRHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-1.0V/Vscf3D_af_Laplace_correction.out  ./DASTRIMTRIM/-1000.VT
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-1.0V/Vhartree3D_af_Laplace_correction.out  ./DASTRIMTRIM/-1000.VH
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-1.0V/Vhartree03D_af_Laplace_correction.out  ./DASTRIMTRIM/-1000.VH0

echo "-500"

cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-0.5V/main.RHO ./DASTRIMTRIM/-500.RHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-0.5V/main.DRHO ./DASTRIMTRIM/-500.DRHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-0.5V/Vscf3D_af_Laplace_correction.out  ./DASTRIMTRIM/-500.VT
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-0.5V/Vhartree3D_af_Laplace_correction.out  ./DASTRIMTRIM/-500.VH
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM-0.5V/Vhartree03D_af_Laplace_correction.out  ./DASTRIMTRIM/-500.VH0

echo "0"

cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM_0.0V/main.RHO ./DASTRIMTRIM/0.RHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM_0.0V/main.DRHO ./DASTRIMTRIM/0.DRHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM_0.0V/Vscf3D_af_Laplace_correction.out  ./DASTRIMTRIM/0.VT
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM_0.0V/Vhartree3D_af_Laplace_correction.out  ./DASTRIMTRIM/0.VH
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM_0.0V/Vhartree03D_af_Laplace_correction.out  ./DASTRIMTRIM/0.VH0

echo "500"

cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+0.5V/main.RHO ./DASTRIMTRIM/500.RHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+0.5V/main.DRHO  ./DASTRIMTRIM/500.DRHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+0.5V/Vscf3D_af_Laplace_correction.out  ./DASTRIMTRIM/500.VT
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+0.5V/Vhartree3D_af_Laplace_correction.out  ./DASTRIMTRIM/500.VH
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+0.5V/Vhartree03D_af_Laplace_correction.out  ./DASTRIMTRIM/500.VH0

echo "1000"

cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+1.0V/main.RHO ./DASTRIMTRIM/1000.RHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+1.0V/main.DRHO  ./DASTRIMTRIM/1000.DRHO
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+1.0V/Vscf3D_af_Laplace_correction.out  ./DASTRIMTRIM/1000.VT
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+1.0V/Vhartree3D_af_Laplace_correction.out  ./DASTRIMTRIM/1000.VH
cp /mako/scratch/pdarancet/DAS_EnforcedSym/DASEnforcedSYM+1.0V/Vhartree03D_af_Laplace_correction.out  ./DASTRIMTRIM/1000.VH0

mkdir BAPATRIMTRIM
echo "BAPATRIMTRIM"

echo "-1000"

cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-1.0V/main.RHO  ./BAPATRIMTRIM/-1000.RHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-1.0V/main.DRHO  ./BAPATRIMTRIM/-1000.DRHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-1.0V/Vscf3D_af_Laplace_correction.out  ./BAPATRIMTRIM/-1000.VT
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-1.0V/Vhartree3D_af_Laplace_correction.out  ./BAPATRIMTRIM/-1000.VH
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-1.0V/Vhartree03D_af_Laplace_correction.out  ./BAPATRIMTRIM/-1000.VH0

echo "-500"

cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-0.5V/main.RHO  ./BAPATRIMTRIM/-500.RHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-0.5V/main.DRHO  ./BAPATRIMTRIM/-500.DRHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-0.5V/Vscf3D_af_Laplace_correction.out  ./BAPATRIMTRIM/-500.VT
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-0.5V/Vhartree3D_af_Laplace_correction.out  ./BAPATRIMTRIM/-500.VH
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM-0.5V/Vhartree03D_af_Laplace_correction.out  ./BAPATRIMTRIM/-500.VH0
echo "0"

cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM_0.0V/main.RHO  ./BAPATRIMTRIM/0.RHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM_0.0V/main.DRHO  ./BAPATRIMTRIM/0.DRHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM_0.0V/Vscf3D_af_Laplace_correction.out ./BAPATRIMTRIM/0.VT
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM_0.0V/Vhartree3D_af_Laplace_correction.out  ./BAPATRIMTRIM/0.VH
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM_0.0V/Vhartree03D_af_Laplace_correction.out  ./BAPATRIMTRIM/0.VH0

echo "500"

cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+0.5V/main.RHO  ./BAPATRIMTRIM/500.RHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+0.5V/main.DRHO ./BAPATRIMTRIM/500.DRHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+0.5V/Vscf3D_af_Laplace_correction.out  ./BAPATRIMTRIM/500.VT
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+0.5V/Vhartree3D_af_Laplace_correction.out  ./BAPATRIMTRIM/500.VH
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+0.5V/Vhartree03D_af_Laplace_correction.out  ./BAPATRIMTRIM/500.VH0

echo "1000"

cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+1.0V/main.RHO  ./BAPATRIMTRIM/1000.RHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+1.0V/main.DRHO  ./BAPATRIMTRIM/1000.DRHO
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+1.0V/Vscf3D_af_Laplace_correction.out  ./BAPATRIMTRIM/1000.VT
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+1.0V/Vhartree3D_af_Laplace_correction.out  ./BAPATRIMTRIM/1000.VH
cp /mako/scratch/pdarancet/BAPA_SYM/BAPAEnforcedSYM+1.0V/Vhartree03D_af_Laplace_correction.out  ./BAPATRIMTRIM/1000.VH0

mkdir HDATRITRIM
echo "HDATRIMTRIM"

echo "-1000"

cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-1.0V/main.RHO  ./HDATRIMTRIM/-1000.RHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-1.0V/main.DRHO  ./HDATRIMTRIM/-1000.DRHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-1.0V/Vscf3D_af_Laplace_correction.out  ./HDATRIMTRIM/-1000.VT
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-1.0V/Vhartree3D_af_Laplace_correction.out  ./HDATRIMTRIM/-1000.VH
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-1.0V/Vhartree03D_af_Laplace_correction.out  ./HDATRIMTRIM/-1000.VH0

echo "-500"

cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-0.5V/main.RHO  ./HDATRIMTRIM/-500.RHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-0.5V/main.DRHO  ./HDATRIMTRIM/-500.DRHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-0.5V/Vscf3D_af_Laplace_correction.out  ./HDATRIMTRIM/-500.VT
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-0.5V/Vhartree3D_af_Laplace_correction.out  ./HDATRIMTRIM/-500.VH
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM-0.5V/Vhartree03D_af_Laplace_correction.out  ./HDATRIMTRIM/-500.VH0

echo "0"

cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM_0.0V/main.RHO  ./HDATRIMTRIM/0.RHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM_0.0V/main.DRHO  ./HDATRIMTRIM/0.DRHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM_0.0V/Vscf3D_af_Laplace_correction.out  ./HDATRIMTRIM/0.VT
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM_0.0V/Vhartree3D_af_Laplace_correction.out  ./HDATRIMTRIM/0.VH
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM_0.0V/Vhartree03D_af_Laplace_correction.out  ./HDATRIMTRIM/0.VH0

echo "500"

cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+0.5V/main.RHO  ./HDATRIMTRIM/500.RHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+0.5V/main.DRHO  ./HDATRIMTRIM/500.DRHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+0.5V/Vscf3D_af_Laplace_correction.out ./HDATRIMTRIM/500.VT
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+0.5V/Vhartree3D_af_Laplace_correction.out  ./HDATRIMTRIM/500.VH
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+0.5V/Vhartree03D_af_Laplace_correction.out  ./HDATRIMTRIM/500.VH0

echo "1000"

cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+1.0V/main.RHO  ./HDATRIMTRIM/1000.RHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+1.0V/main.DRHO  ./HDATRIMTRIM/1000.DRHO
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+1.0V/Vscf3D_af_Laplace_correction.out  ./HDATRIMTRIM/1000.VT
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+1.0V/Vhartree3D_af_Laplace_correction.out  ./HDATRIMTRIM/1000.VH
cp /mako/scratch/pdarancet/HDA-D_SYM/HDADEnforcedSYM+1.0V/Vhartree03D_af_Laplace_correction.out  ./HDATRIMTRIM/1000.VH0

mkdir BPTRIMTRIM
echo "BPTRIMTRIM"

echo "-1000"

cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-1.0V/main.RHO ./BPTRIMTRIM/-1000.RHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-1.0V/main.DRHO ./BPTRIMTRIM/-1000.DRHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-1.0V/Vscf3D_af_Laplace_correction.out ./BPTRIMTRIM/-1000.VT
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-1.0V/Vhartree3D_af_Laplace_correction.out ./BPTRIMTRIM/-1000.VH
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-1.0V/Vhartree03D_af_Laplace_correction.out ./BPTRIMTRIM/-1000.VH0

echo "-500"

cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-0.5V/main.RHO ./BPTRIMTRIM/-500.RHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-0.5V/main.DRHO ./BPTRIMTRIM/-500.DRHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-0.5V/Vscf3D_af_Laplace_correction.out ./BPTRIMTRIM/-500.VT
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-0.5V/Vhartree3D_af_Laplace_correction.out ./BPTRIMTRIM/-500.VH
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim-0.5V/Vhartree03D_af_Laplace_correction.out ./BPTRIMTRIM/-500.VH0

echo "0"

cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim_0.0V/main.RHO ./BPTRIMTRIM/0.RHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim_0.0V/main.DRHO ./BPTRIMTRIM/0.DRHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim_0.0V/Vscf3D_af_Laplace_correction.out ./BPTRIMTRIM/0.VT
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim_0.0V/Vhartree3D_af_Laplace_correction.out ./BPTRIMTRIM/0.VH
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim_0.0V/Vhartree03D_af_Laplace_correction.out ./BPTRIMTRIM/0.VH0

echo "500"

cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+0.5V/main.RHO ./BPTRIMTRIM/500.RHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+0.5V/main.DRHO ./BPTRIMTRIM/500.DRHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+0.5V/Vscf3D_af_Laplace_correction.out ./BPTRIMTRIM/500.VT
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+0.5V/Vhartree3D_af_Laplace_correction.out ./BPTRIMTRIM/500.VH
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+0.5V/Vhartree03D_af_Laplace_correction.out ./BPTRIMTRIM/500.VH0

echo "1000"

cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+1.0V/main.RHO ./BPTRIMTRIM/1000.RHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+1.0V/main.DRHO ./BPTRIMTRIM/1000.DRHO
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+1.0V/Vscf3D_af_Laplace_correction.out ./BPTRIMTRIM/1000.VT
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+1.0V/Vhartree3D_af_Laplace_correction.out ./BPTRIMTRIM/1000.VH
cp /mako/scratch/pdarancet/BP_constr_TrimTrim/BP_SY_TrimTrim+1.0V/Vhartree03D_af_Laplace_correction.out ./BPTRIMTRIM/1000.VH0


mkdir BPVHGTRIMAD
echo "BPVHGTRIMAD"

echo "-1000"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-1000/main.RHO ./BPVHGTRIMAD/-1000.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-1000/main.DRHO ./BPVHGTRIMAD/-1000.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-1000/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-1000.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-1000/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-1000.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-1000/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-1000.VH0
echo "-900"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-900/main.RHO ./BPVHGTRIMAD/-900.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-900/main.DRHO ./BPVHGTRIMAD/-900.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-900/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-900.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-900/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-900.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-900/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-900.VH0
echo "-800"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-800/main.RHO ./BPVHGTRIMAD/-800.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-800/main.DRHO ./BPVHGTRIMAD/-800.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-800/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-800.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-800/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-800.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-800/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-800.VH0
echo "-700"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-700/main.RHO ./BPVHGTRIMAD/-700.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-700/main.DRHO ./BPVHGTRIMAD/-700.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-700/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-700.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-700/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-700.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-700/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-700.VH0
echo "-600"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-600/main.RHO ./BPVHGTRIMAD/-600.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-600/main.DRHO ./BPVHGTRIMAD/-600.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-600/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-600.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-600/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-600.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-600/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-600.VH0
echo "-500"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-500/main.RHO ./BPVHGTRIMAD/-500.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-500/main.DRHO ./BPVHGTRIMAD/-500.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-500/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-500.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-500/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-500.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-500/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-500.VH0
echo "-400"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-400/main.RHO ./BPVHGTRIMAD/-400.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-400/main.DRHO ./BPVHGTRIMAD/-400.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-400/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-400.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-400/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-400.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-400/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-400.VH0
echo "-300"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-300/main.RHO ./BPVHGTRIMAD/-300.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-300/main.DRHO ./BPVHGTRIMAD/-300.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-300/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-300.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-300/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-300.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-300/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-300.VH0
echo "-200"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-200/main.RHO ./BPVHGTRIMAD/-200.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-200/main.DRHO ./BPVHGTRIMAD/-200.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-200/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-200.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-200/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-200.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-200/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-200.VH0
echo "-100"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-100/main.RHO ./BPVHGTRIMAD/-100.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-100/main.DRHO ./BPVHGTRIMAD/-100.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-100/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/-100.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-100/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/-100.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_-100/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/-100.VH0
echo "0"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_0/main.RHO ./BPVHGTRIMAD/0.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_0/main.DRHO ./BPVHGTRIMAD/0.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_0/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/0.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_0/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/0.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_0/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/0.VH0
echo "100"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_100/main.RHO ./BPVHGTRIMAD/100.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_100/main.DRHO ./BPVHGTRIMAD/100.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_100/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/100.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_100/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/100.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_100/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/100.VH0
echo "200"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_200/main.RHO ./BPVHGTRIMAD/200.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_200/main.DRHO ./BPVHGTRIMAD/200.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_200/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/200.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_200/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/200.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_200/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/200.VH0
echo "300"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_300/main.RHO ./BPVHGTRIMAD/300.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_300/main.DRHO ./BPVHGTRIMAD/300.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_300/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/300.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_300/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/300.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_300/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/300.VH0
echo "400"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_400/main.RHO ./BPVHGTRIMAD/400.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_400/main.DRHO ./BPVHGTRIMAD/400.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_400/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/400.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_400/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/400.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_400/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/400.VH0
echo "500"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_500/main.RHO ./BPVHGTRIMAD/500.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_500/main.DRHO ./BPVHGTRIMAD/500.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_500/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/500.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_500/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/500.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_500/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/500.VH0
echo "600"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_600/main.RHO ./BPVHGTRIMAD/600.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_600/main.DRHO ./BPVHGTRIMAD/600.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_600/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/600.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_600/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/600.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_600/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/600.VH0
echo "700"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_700/main.RHO ./BPVHGTRIMAD/700.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_700/main.DRHO ./BPVHGTRIMAD/700.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_700/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/700.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_700/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/700.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_700/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/700.VH0
echo "800"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_800/main.RHO ./BPVHGTRIMAD/800.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_800/main.DRHO ./BPVHGTRIMAD/800.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_800/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/800.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_800/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/800.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_800/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/800.VH0
echo "900"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_900/main.RHO ./BPVHGTRIMAD/900.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_900/main.DRHO ./BPVHGTRIMAD/900.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_900/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/900.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_900/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/900.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_900/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/900.VH0
echo "1000"
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_1000/main.RHO ./BPVHGTRIMAD/1000.RHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_1000/main.DRHO ./BPVHGTRIMAD/1000.DRHO
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_1000/Vscf3D_af_Laplace_correction.out ./BPVHGTRIMAD/1000.VT
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_1000/Vhartree3D_af_Laplace_correction.out ./BPVHGTRIMAD/1000.VH
cp /mako/scratch/pdarancet/BP_VeryHighG_TrimAd/PyridineBias_1000/Vhartree03D_af_Laplace_correction.out ./BPVHGTRIMAD/1000.VH0


cd ..
echo "tar"
tar -zcvf Transfer2.gz Transfer2
echo "Done"



