#!/bin/bash

rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" Carbon:~/DATA_PPV/* ~/DATA/DATA_PPV/
rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" Carbon:~/DATA_JGuest/* ~/DATA/DATA_JGuest/
rsync -avtuz --exclude "*CHG" --exclude "*CHGCAR"  Carbon:~/DATA_Erratum/* ~/DATA/DATA_Erratum/
rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" --exclude "*CHG" --exclude "*CHGCAR" --exclude "*WAVECAR"  Carbon:~/DATA_Boron/* ~/DATA/DATA_Boron/
rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" --exclude "*CHG" --exclude "*CHGCAR" --exclude "*WAVECAR" --exclude "*TSHS" --exclude "*CLOCK"  --exclude "*TSDE" --exclude "*.DM" Carbon:~/DATA_FieldInducedBondBreaking/* ~/DATA/DATA_FieldInducedBondBreaking/
rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" --exclude "*CHG" --exclude "*CHGCAR" --exclude "*WAVECAR" --exclude "*TSHS" --exclude "*CLOCK"  --exclude "*TSDE" --exclude "*.DM" Carbon:~/DATA_MVCdSe/* ~/DATA/DATA_MVCdSe/
rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" --exclude "*CHG" --exclude "*CHGCAR" --exclude "*WAVECAR" --exclude "*TSHS" --exclude "*CLOCK"  --exclude "*TSDE" --exclude "*.DM" Carbon:~/DATA_RamanTransport/* ~/DATA/DATA_RamanTransport/
rsync -avtuz --exclude "*INPUT*" --exclude "*.GF" --exclude "*.psf"  --exclude "*ion" --exclude "*NON_TRIMMED_KP_LIST" --exclude "*OCCS" --exclude "*xml" --exclude "*log" --exclude "*err" --exclude "*CHG" --exclude "*CHGCAR" --exclude "*WAVECAR" --exclude "*TSHS" --exclude "*CLOCK"  --exclude "*TSDE" --exclude "*.DM" Carbon:~/DATA_Saw/* ~/DATA/DATA_Saw/
